version: '3'
services:

  apache24:
    image: degobbis/apache24-alpine
    build:
      context: .
      dockerfile: ./.builds/httpd/apache24/Dockerfile
      args:
        MY_TZ: ${MY_TZ:-UTC}
    container_name: apache24
    links:
      - mysql
      - php56-fpm
      - php73-fpm
      - php74-fpm
      - mailhog
    volumes:
      - ./.config/httpd/apache24/httpd.conf /usr/local/apache2/conf/httpd.conf
      - ./.config/httpd/apache24/conf.d:/usr/local/apache2/conf.d
      - ./.config/httpd/apache24/vhosts:/usr/local/apache2/vhosts
      - ${LOG_DIR:-./.data/logs}:/var/log
      - ${WWW_BASEDIR:-./.data/www}:/srv/www
      - pma:/srv/pma
      - phpsocket:/run/php
    ports:
      - "80:${MAP_POT_80:-8074}"
      - "8000:8000"
      - "8056:8056"
      - "8073:8073"
      - "8074:8074"
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
    networks:
      - lampp

  php56-fpm:
    image: degobbis/php56-fpm-alpine
    build:
      context: .
      dockerfile: ./.builds/php/php56-fpm/Dockerfile
      args:
        MY_TZ: ${MY_TZ:-UTC}
    container_name: php56-fpm
    links:
      - mailhog
      - mysql
    volumes:
      - ./.config/php/php-fpm-global-overrides.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-global-overrides.conf
      - ./.config/php/php56/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zzzz-php-fpm-overrides.conf
      - ./.config/php/php-global-overrides.ini:/usr/local/etc/php/conf.d/00-php-global-overrides.ini
      - ./.config/php/php56/php-version-overrides.ini:/usr/local/etc/php/conf.d/99-php-version-overrides.ini
      - ${WWW_BASEDIR:-./.data/www}:/srv/www
      - phpsocket:/run/php
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
    networks:
      - lampp

  php73-fpm:
    image: degobbis/php73-fpm-alpine
    build:
      context: .
      dockerfile: ./.builds/php/php73-fpm/Dockerfile
      args:
        MY_TZ: ${MY_TZ:-UTC}
    container_name: php73-fpm
    links:
      - mailhog
      - mysql
    volumes:
      - ./.config/php/php-fpm-global-overrides.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-global-overrides.conf
      - ./.config/php/php73/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zzzz-php-fpm-overrides.conf
      - ./.config/php/php-global-overrides.ini:/usr/local/etc/php/conf.d/00-php-global-overrides.ini
      - ./.config/php/php73/php-version-overrides.ini:/usr/local/etc/php/conf.d/99-php-version-overrides.ini
      - ${WWW_BASEDIR:-./.data/www}:/srv/www
      - phpsocket:/run/php
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
    networks:
      - lampp

  php74-fpm:
    image: degobbis/php74-fpm-alpine
    build:
      context: .
      dockerfile: ./.builds/php/php74-fpm/Dockerfile
      args:
        MY_TZ: ${MY_TZ:-UTC}
    container_name: php74-fpm
    links:
      - mailhog
      - mysql
    volumes:
      - ./.config/php/php-fpm-global-overrides.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-global-overrides.conf
      - ./.config/php/php74/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zzzz-php-fpm-overrides.conf
      - ./.config/php/php-global-overrides.ini:/usr/local/etc/php/conf.d/00-php-global-overrides.ini
      - ./.config/php/php74/php-version-overrides.ini:/usr/local/etc/php/conf.d/99-php-version-overrides.ini
      - ${WWW_BASEDIR:-./.data/www}:/srv/www
      - phpsocket:/run/php
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
    networks:
      - lampp

  mysql:
    image: degobbis/mariadb-alpine
    build:
      context: .
      dockerfile: ./.builds/db/mariadb/Dockerfile
      args:
        MY_TZ: ${MY_TZ:-UTC}
    container_name: mysql
    restart: unless-stopped
    volumes:
      - db-data-dir:/var/lib/mysql
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD:-root}
    ports:
      - "3306:3306"
    networks:
      - lampp

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - lampp

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    container_name: phpmyadmin
    links:
      - mysql
    volumes:
      - ./.config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - pma:/var/www/html
    environment:
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD:-root}
    networks:
      - lampp

volumes:
  pma:
  db-data-dir:
  phpsocket:

networks:
  lampp:
